DROP TABLE CATEGORYTABLE;
CREATE TABLE CATEGORYTABLE (CATEGORY VARCHAR2(40));
INSERT INTO CATEGORYTABLE VALUES('Programming Language');
INSERT INTO CATEGORYTABLE VALUES('Web Development');
INSERT INTO CATEGORYTABLE VALUES('Enterprise Solutions');
INSERT INTO CATEGORYTABLE VALUES('Operating System');
INSERT INTO CATEGORYTABLE VALUES('Computer Hardware');
INSERT INTO CATEGORYTABLE VALUES('Computer Software');
COMMIT;