DROP TABLE ORDERLIST;
DROP TABLE ORDERLIST;
CREATE TABLE ORDERLIST(ID VARCHAR2(20) NOT NULL, PASSWD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,ADDRESS VARCHAR2(50) NOT NULL,
PHONE VARCHAR2(20) NOT NULL, ISBN VARCHAR2(20) NOT NULL,
TITLE VARCHAR2(50) NOT NULL, QUANTITY NUMBER(4)NOT NULL, PRICE NUMBER(6));
COMMIT;
;